name: ageapp
description: Aplicacion de AGEUP

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter   
  url_launcher: ^4.2.0+3
  flappy_search_bar: 1.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:




  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/AGEUP.jpg
    - assets/foto4.jpg
    - assets/foto3.jpg
    - assets/foto2.jpg
    - assets/fondo.jpg
    - assets/logooficial2.png
    - img_documents/estudio-biblico-creativo.jpg
    - img_documents/la-paz-del-perdon.jpg
    - img_documents/desafio-a-servir.jpg
    - img_documents/tendriamos-que-haber-gritado.jpg
    - img_documents/mision-de-dios.jpg
    - img_documents/mision-en-transformacion.jpg
    - img_documents/precio-de-la-gracia.jpg
    - img_documents/escritos-esenciales.jpg
    - img_documents/vida-en-comunidad.jpg
    - img_documents/etica.jpg
    - img_documents/lectio-divina.jpg
    - img_documents/existe-dios.jpg
    - img_documents/cristianismo.jpg
    - img_documents/el-principio-de-las-cosas.jpg
    - img_documents/la-mujer-en-el-cristianismo.jpg
    - img_documents/dinero-y-poder.jpg
    - img_documents/la-edad-tecnica.jpg
    - img_documents/cristianismo-y-ciencia.jpg
    - img_documents/progreso-peregrino.jpg
    - img_documents/sentido-de-la-vida.jpg
    - img_documents/asi-leo-la-biblia.jpg
    - img_documents/creer-es-tambien-pensar.jpg
    - img_documents/cristianismo-basico.jpg
    - img_documents/el-cristiano-contemporneo.jpg
    - img_documents/estudiantes-de-la-palabra.jpg
    - img_documents/identidad-evangelica.jpg
    - img_documents/la-cruz-de-cristo.jpg
    - img_documents/desafios-del-cristiano.jpg
    - img_documents/espiritu-santo.jpg
    - img_documents/sobre-la-roca.jpg
    - img_documents/sermon-del-monte.jpg
    - img_documents/juan-4.jpg
    - img_documents/lucas-3.jpg
    - img_documents/marcos-2.jpg
    - img_documents/mateo-1.jpg
    - img_documents/grupos-de-jesus.jpg
    - img_documents/jesus-aproximacion.jpg
    - img_documents/jesus-nazaret.jpg
    - img_documents/rompamos-silencio.jpg
    - img_documents/pentateuco.jpg
    - img_documents/el-pastor-como-consejero.jpg
    - img_documents/se-hizo-hombre.jpg
    - img_documents/todos-somos-teologos.jpg
    - img_documents/que-es-mision-integral.jpg
    - img_documents/bases-biblicas.jpg
    - img_documents/el-evangelio-hoy.jpg
    - img_documents/mision-integral.jpg
    - img_documents/evangelizar-hoy.jpg
    - img_documents/la-chispa-y-la-llama.jpg
    - img_documents/tiempo-de-mision.jpg
    - img_documents/vida-de-fe.jpg
    - img_documents/abraham.jpg
    - img_documents/contagiar-una-vision-misionera.jpg
    - img_documents/daniel.jpg
    - img_documents/elias.jpg
    - img_documents/esdras-y-nehemias.jpg
    - img_documents/espacios-de-formacion.jpg
    - img_documents/estudio-biblico-inductivo.jpg
    - img_documents/guia-celulas-estudio-biblico.jpg
    - img_documents/guia-encuentros-virtuales.jpg
    - img_documents/jonas.jpg
    - img_documents/moises.jpg
    - img_documents/mujeres-que-esperan.jpg
    - img_documents/pablo.jpg
    - img_documents/jesucristo-vol-1.jpg
    - img_documents/jesucristo-vol-2.jpg
    - img_documents/jesucristo-vol-3.jpg
    - img_documents/jesucristo-vol-4.jpg
    - img_documents/vidas-militantes.jpg
    - img_documents/sermon-del-monte-bolivia.jpg
    - img_documents/se-diferente.jpg
    - img_documents/modelo-de-mision.jpg
    - img_documents/fe-y-crisis-de-fe.jpg
    - img_documents/alabanza-y-sabiduria.jpg
    - img_documents/cuatro-hombres.jpg
    - img_documents/vivir-por-la-fe.jpg
    - img_documents/sufrimiento.jpg
    - img_documents/contagiar-una-vision-misionera.jpg
    - img_documents/gaia.jpg

    - assets/fotorobin.jpg
    - assets/fotoaracely.jpg
    - assets/fotojuank.jpg

    - assets/fotojdn.jpg
    - assets/RCC.jpg
    - assets/RN.jpg
    - assets/RCO.jpg
    - assets/RO.png
    - assets/RS.jpg
    - assets/mapa.jpg
  # fotos de regiones
    - assets/fotovu.jpg
    - assets/costacentro2.jpg
    - assets/fondocentrooriente.jpg
    - assets/centrooriente2.jpg
    - assets/fondonorte.jpg
    - assets/norte2.jpg
    - assets/fondooriente.jpg
    - assets/oriente2.jpg
    - assets/fondosur.jpg
    - assets/sur2.jpg

    # fotos de contactos
    - assets/fotorobin.jpg
    - assets/fotojuank.jpg
    - assets/fotodanny.jpg
    - assets/fotobeula.jpg
    - assets/fotocriss.jpg
    - assets/fotoroberto.jpg
    - assets/fotorut.jpg
    - assets/fotomisael.jpg
    - assets/fotoaracely.jpg
    - assets/fotojhoss.jpg
    # imagenes para el juego
    - assets/images/cross.png
    - assets/images/circle.png
    - assets/images/edit.png


  fonts:
    - family:  SocialMedia
      fonts:
        - asset: fonts/SocialMedia.ttf