name: ageapp
description: Aplicacion de AGEUP

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter   
  url_launcher: ^4.2.0+3
  flappy_search_bar: 1.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:




  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/AGEUP.jpg
    - assets/foto4.jpg
    - assets/foto3.jpg
    - assets/foto2.jpg
    - assets/fondo.jpg
    - assets/logooficial2.png
    - img_books/estudio-biblico-creativo.jpg
    - img_books/la-paz-del-perdon.jpg
    - img_books/desafio-a-servir.jpg
    - img_books/tendriamos-que-haber-gritado.jpg
    - img_books/mision-de-dios.jpg
    - img_books/mision-en-transformacion.jpg
    - img_books/precio-de-la-gracia.jpg
    - img_books/escritos-esenciales.jpg
    - img_books/vida-en-comunidad.jpg
    - img_books/etica.jpg
    - img_books/lectio-divina.jpg
    - img_books/existe-dios.jpg
    - img_books/cristianismo.jpg
    - img_books/el-principio-de-las-cosas.jpg
    - img_books/la-mujer-en-el-cristianismo.jpg
    - img_books/dinero-y-poder.jpg
    - img_books/la-edad-tecnica.jpg
    - img_books/cristianismo-y-ciencia.jpg
    - img_books/progreso-peregrino.jpg
    - img_books/sentido-de-la-vida.jpg
    - img_books/asi-leo-la-biblia.jpg
    - img_books/creer-es-tambien-pensar.jpg
    - img_books/cristianismo-basico.jpg
    - img_books/el-cristiano-contemporneo.jpg
    - img_books/estudiantes-de-la-palabra.jpg
    - img_books/identidad-evangelica.jpg
    - img_books/la-cruz-de-cristo.jpg
    - img_books/desafios-del-cristiano.jpg
    - img_books/espiritu-santo.jpg
    - img_books/sobre-la-roca.jpg
    - img_books/sermon-del-monte.jpg
    - img_books/juan-4.jpg
    - img_books/lucas-3.jpg
    - img_books/marcos-2.jpg
    - img_books/mateo-1.jpg
    - img_books/grupos-de-jesus.jpg
    - img_books/jesus-aproximacion.jpg
    - img_books/jesus-nazaret.jpg
    - img_books/rompamos-silencio.jpg
    - img_books/pentateuco.jpg
    - img_books/el-pastor-como-consejero.jpg
    - img_books/se-hizo-hombre.jpg
    - img_books/todos-somos-teologos.jpg
    - img_books/que-es-mision-integral.jpg
    - img_books/bases-biblicas.jpg
    - img_books/el-evangelio-hoy.jpg
    - img_books/mision-integral.jpg
    - img_books/evangelizar-hoy.jpg
    - img_books/la-chispa-y-la-llama.jpg
    - img_books/tiempo-de-mision.jpg

#la sangribooks/a papaaaaaaaaaa

=======
    - assets/fotorobin.jpg
    - assets/fotoaracely.jpg
    - assets/fotojuank.jpg
    - assets/fotojdn.jpg
    - assets/RCC.jpg
    - assets/RN.jpg
    - assets/RCO.jpg
    - assets/RO.jpg
    - assets/RS.jpg
    - assets/mapa.jpg
    # fotos de regiones
    - assets/fotovu.jpg
    - assets/costacentro2.jpg
    - assets/fondocentrooriente.jpg
    - assets/centrooriente2.jpg
    - assets/fondonorte.jpg
    - assets/norte2.jpg
    - assets/fondooriente.jpg
    - assets/oriente2.jpg
    - assets/fondosur.jpg
    - assets/sur2.jpg
#la sangria papaaaaaaaaaa
  fonts:
    - family:  SocialMedia
      fonts:
        - asset: fonts/SocialMedia.ttf