name: ageapp
description: Aplicacion de AGEUP

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
<<<<<<< HEAD
    sdk: flutter 

    
  url_launcher: ^4.2.0+3
  flappy_search_bar: 1.4.1


=======
    sdk: flutter
  url_launcher: ^4.2.0+3
>>>>>>> 3cb4569b28c86c017abdb3bb2e06b1117029cca2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:




  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/AGEUP.jpg
    - assets/foto4.jpg
    - assets/foto3.jpg
    - assets/foto2.jpg
    - assets/fondo.jpg
<<<<<<< HEAD












    - res/estudio-biblico-creativo.jpg
    - res/la-paz-del-perdon.jpg
    - res/desafio-a-servir.jpg
    - res/tendriamos-que-haber-gritado.jpg
    - res/mision-de-dios.jpg
    - res/mision-en-transformacion.jpg
    - res/precio-de-la-gracia.jpg
    - res/escritos-esenciales.jpg
    - res/vida-en-comunidad.jpg
    - res/etica.jpg
    - res/lectio-divina.jpg
    - res/existe-dios.jpg
    - res/cristianismo.jpg
    - res/el-principio-de-las-cosas.jpg
    - res/la-mujer-en-el-cristianismo.jpg
    - res/dinero-y-poder.jpg
    - res/la-edad-tecnica.jpg
    - res/cristianismo-y-ciencia.jpg
    - res/progreso-peregrino.jpg
    - res/sentido-de-la-vida.jpg
    - res/asi-leo-la-biblia.jpg
    - res/creer-es-tambien-pensar.jpg
    - res/cristianismo-basico.jpg
    - res/el-cristiano-contemporneo.jpg
    - res/estudiantes-de-la-palabra.jpg
    - res/identidad-evangelica.jpg
    - res/la-cruz-de-cristo.jpg
    - res/desafios-del-cristiano.jpg
    - res/espiritu-santo.jpg
    - res/sobre-la-roca.jpg
    - res/sermon-del-monte.jpg
    - res/juan-4.jpg
    - res/lucas-3.jpg
    - res/marcos-2.jpg
    - res/mateo-1.jpg
    - res/grupos-de-jesus.jpg
    - res/jesus-aproximacion.jpg
    - res/jesus-nazaret.jpg
    - res/rompamos-silencio.jpg
    - res/pentateuco.jpg
    - res/el-pastor-como-consejero.jpg
    - res/se-hizo-hombre.jpg
    - res/todos-somos-teologos.jpg
    - res/que-es-mision-integral.jpg
    - res/bases-biblicas.jpg
    - res/el-evangelio-hoy.jpg
    - res/mision-integral.jpg
    - res/evangelizar-hoy.jpg
    - res/la-chispa-y-la-llama.jpg
    - res/tiempo-de-mision.jpg
    
    

#fuente sangria 
=======
    - assets/logo.jpg
    - assets/logooficial2.png
#la sangria papaaaaaaaaaa
>>>>>>> 3cb4569b28c86c017abdb3bb2e06b1117029cca2
  fonts:
    - family:  SocialMedia
      fonts:
        - asset: fonts/SocialMedia.ttf