class Documents {
  String title,
      writer,
      year,
      image,
      link ,
      description;
  int pages;
  double rating;

  Documents(
      this.title, this.writer, this.year, this.image, this.rating, this.pages, this.link, this.description);
}

final List<Documents> documents = [
  Documents('Abraham la vida de fe 2da edicion', 'AGEUP',
      'Año: 1993', 'img_documents/vida-de-fe.jpg', 3, 22,'https://drive.google.com/file/d/1YMqlNIl4AoWUmbUjluuq_cUV9-nLhP9V/view?usp=sharing',
      'Este material da a conocer de manera resumida sobre algunas figuras del antiguo testamento que, con su vida ha mostrado un agrado a DIOS y un desafio para nuestra travesia de militancia'),
  Documents('Abraham La vida de fe 1ra edicion', 'CIEE',
      'Año: 1971', 'img_documents/abraham.jpg', 3, 12,'https://drive.google.com/file/d/1Renn0rmZCXRoMPtiwzp1brIyRaC0IjeD/view?usp=sharing',
      'Este material da a conocer de manera resumida sobre algunas figuras del antiguo testamento que, con su vida ha mostrado un agrado a DIOS y un desafio para nuestra travesia de militancia'),
  Documents('Contagiar una  visión misionera a los universitarios', 'AGEUP',
      'Año: 2010', 'img_documents/contagiar-una-vision-misionera.jpg', 3, 8,'https://drive.google.com/file/d/156hQwMhNCTyg8Hl9UjjaSO711UzSAjfX/view?usp=sharing',
      'Un movimiento estudiantil donde la iniciativa y la responsabilidad respecto al testimonio y a la evangelización en la universidad descansa principalmente sobre los hombros de los mismos estudiantes. Este es un movimiento esencialmente de estudiantes y para estudiantes1'),
  Documents('Daniel  estadista, profeta y santo', 'Pedro Arana Quiroz',
      'Año: 1972', 'img_documents/daniel.jpg', 3, 12,'https://drive.google.com/file/d/1GrYL1To_iZ49cXeEg7DwX7z0fTvsm0zE/view?usp=sharing',
      'Material que nos permite evaluar la vida de Daniel es de manera bíblica su exilio en Babilonia, así como sus profecías, formacion, etc.'),
  Documents('Elias  la vida de un transtornador', 'Pedro Arana Quiroz',
      'Año: 1971', 'img_documents/elias.jpg', 3, 8,'https://drive.google.com/file/d/1MNej7eDSp5XzkdqJ8lFyCq6ZJ9BmxvYK/view?usp=sharing',
      'Esta serie fue creado por Pedro Arana Quiroz, secreatario regional para los paises Boliviaranos y del Caribe'),
  Documents('Esdras y Nehemias  la vida militante en el A.T.', 'AGEUP',
      'Año: 1972', 'img_documents/esdras-y-nehemias.jpg', 3, 8,'https://drive.google.com/file/d/1oVeF_BsvO29nuxa_2TAtYfL-pdAUUZM8/view?usp=sharing',
      'Este estudio es publicado originalmente por el Ciruclo Bíblico Universitario de Lima, Perú'),
  Documents('Espacios de formación', 'AGEUP',
      'Año: 2010', 'img_documents/espacios-de-formacion.jpg', 3, 4,'https://drive.google.com/file/d/1qIcTMnPll_CMiXY8QDf0ZVDNBVhV_Z1u/view?usp=sharing',
      'Guia de algunos Niveles de espacio de formación de la Asociacion de grupos evangelicos universitarios del Perú - AGEUP'),
  Documents('Estudio bíblico inductivo', 'AGEUP',
      'Año: 2011', 'img_documents/estudio-biblico-inductivo.jpg', 3, 9,'https://drive.google.com/file/d/1BSIpUJ8pNuaDHClkVZNdPE9_l4s2lBC2/view?usp=sharing',
      'El metodo inductivo ha sido dentro de la comunidad internacional de estudiantes evangelicos, una forma de estudiar a profundidad la biblia, siendo el estudio de la biblia uno de sus ejes y punto de partida'),
  Documents('Guia celulas estudio bíblico', 'AGEUP',
      'Año: 1989', 'img_documents/guia-celulas-estudio-biblico.jpg', 3, 37,'https://drive.google.com/file/d/1Iwsj0qpJkxOmgmaIWXbZ6vGjdXv1wA6E/view?usp=sharing',
      'Una caracteristica de nuestro movimiento ha sido la presentacion viva del evangelio en la universidades y otros centros de educacion superior a traves de pequeños grupos de testimonio. Por medio de ellas la comunidad evangelica tendra una presencia en cada facultad.'),
  Documents('Guia para encuentros bíblicos virtuales', 'AGEUP',
      'Año: 2020', 'img_documents/guia-encuentros-virtuales.jpg', 3, 20,'https://drive.google.com/file/d/18VjpiG1Y6PD8AfoV_Xf162Bn4XbBtHuF/view?usp=sharing',
      'Guia elaborada en la region centro oriente, brindando la facilidad para motivar a los encuentros, dialogos y estudios de la biblia usando como herramienta la tecnologia'),
  Documents('Jonas  profeta y patriota', 'Pedro Arana Quiroz',
      'Año: 1971', 'img_documents/jonas.jpg', 3, 8,'https://drive.google.com/file/d/133oLLrNomlDM7TFXIu_ly9pB86kdiLMl/view?usp=sharing',
      'Esta serie fue creado por Pedro Arana Quiroz, secreatario regional para los paises Boliviaranos y del Caribe'),
  Documents('Moises su preparacion y vocacion', 'CIEE',
      'Año: 1971', 'img_documents/moises.jpg', 3, 8,'https://drive.google.com/file/d/1H7fIfWg0qGZzI4IrKweIPRf_VO-2W4eF/view?usp=sharing',
      'Material elabora por la comunidad internacional de estudiantes'),
  Documents('Mujeres que esperaban en Dios', 'Felicity Houghton',
      'Año: 1973', 'img_documents/mujeres-que-esperan.jpg', 3, 17,'https://drive.google.com/file/d/1gqSCccBCzTCI5iRVlsVyQSZh6pXTRDuE/view?usp=sharing',
      'Esta serie fue presentada por Fecility Houghton, secretaria viajera de los grupos biblicos universitarios de Chile'),
  Documents('Pablo de Tarso, vida y servicio de un intelectual cristiano', 'CIEE',
      'Año: 1977', 'img_documents/pablo.jpg', 3, 13,'https://drive.google.com/file/d/1adwVQ9L8Xys8KJKkpI3ypyV7GF_QK_bz/view?usp=sharing',
      'Este folleto fue preparado por la comunidad internacional de estudiante evangelicos (CIEE'),
  Documents('Vol 01 Jesucristo nuestro señor viviente', 'AGEUP',
      'Año: 1971', 'img_documents/jesucristo-vol-1.jpg', 3, 29,'https://drive.google.com/file/d/1nks2JLboKtuVjseOuZLzJT1zFSvkT0OQ/view?usp=sharing',
      'Esta serie fue preparada por la Asosiacion de grupos evangelicos universitarios del Perú (AGEUP) para labor de evangelización de los circulos biblicos universitarios en 1967'),
  Documents('Vol 02 Jesucristo nuestro fundamento', 'AGEUP',
      'Año: 1971', 'img_documents/jesucristo-vol-2.jpg', 3, 12,'https://drive.google.com/file/d/1h3fvw5WVBQyBTZpfCMlcowod3eLzaX5t/view?usp=sharing',
      'Esta serie fue preparada por la Asosiacion de grupos evangelicos universitarios del Perú (AGEUP) para labor de evangelización de los circulos biblicos universitarios en 1967'),
  Documents('Vol 03  Jesucristo maestro y rey', 'AGEUP',
      'Año: 1971', 'img_documents/jesucristo-vol-3.jpg', 3, 11,'https://drive.google.com/file/d/1X71ZWT2NUga3AJxGXvXVg3z8m1Cu1AiZ/view?usp=sharing',
      'Esta serie fue preparada por la Asosiacion de grupos evangelicos universitarios del Perú (AGEUP) para labor de evangelización de los circulos biblicos universitarios en 1967'),
  Documents('Vol 04  Jesus farsante, demente o Dios', 'AGEUP',
      'Año: 1971', 'img_documents/jesucristo-vol-4.jpg', 3, 11,'https://drive.google.com/file/d/1TBi5wjFKlTIWm_DunMdxdIwBWhnnBln8/view?usp=sharing',
      'Esta serie fue preparada por la Asosiacion de grupos evangelicos universitarios del Perú (AGEUP) para labor de evangelización de los circulos biblicos universitarios en 1967'),
  Documents('Vidas militantes  del nuevo testamento', 'CIEE',
      'Año: 1972', 'img_documents/vidas-militantes.jpg', 3, 9,'https://drive.google.com/file/d/1gNWamz3acKMmTUB5QQndtxEy5zH1fhVc/view?usp=sharing',
      'Esta serie fue presentado por Juan MacPherson M. Presidente del comite administrativo de la Asociacion de grupos evangelicos universitarios del Perú y profesor del Colegio "San Andres" en Lima'),
  Documents('Estudios sobre el sermon del monte', 'CCU Bolivia',
      'Año: 1985', 'img_documents/sermon-del-monte-bolivia.jpg', 3, 42,'https://drive.google.com/file/d/18vmgrWXLMVjNfNBHrOf85resJ5RIRERY/view?usp=sharing',
      'Los diez estudios en este librito abarcan la mayor parte de los capitulos 5 al 7 del evangelio de Mateo, conocido como "el sermon del Monte". en este mensaje conciso pero contudente, Jesús nos descubre tanto las promesas como las demandas que ofrece el Reino de Dios'),
  Documents('Pero tu: se diferente', 'CCU Bolivia',
      'Año: 1985', 'img_documents/se-diferente.jpg', 3, 36,'https://drive.google.com/file/d/1Np8mgItQT25y6t1BNmB4VXFwy_uScp-V/view?usp=sharing',
      'Esta porcion presenta seis estudios biblicos en totalidad de la 2da epistola de Pablo a Timoteo. Cada estudio presenta una dinamica de apertura, un pasaje biblico y una seccion de preguntas correspondientes al tema.'),
  Documents('CBU modelo de mision', 'Dario Lopez',
      'Año: 2008', 'img_documents/modelo-de-mision.jpg', 3, 16,'https://drive.google.com/file/d/1pymY9fLPVj81D5ej5HXw4-hwlT3kL-aa/view?usp=sharing',
      'Bíblicamente sabemos que los cristianos han sido colocados en el mundo por la Gracia de Dios para que le confiesen visiblemente, anunciando y viviendo su verdad en medio las verdades relativas y la mentira de los proyectos humanos. Como iglesia somos luz y sal al interior de los acontecimientos historicos y hemos sido llamados a actuar como fermente de camino y como embajadores de la Gracia infinita de nuestro Dios'),
  Documents('Fe y crisis de fe', 'CIEE',
      'Año: 1976', 'img_documents/fe-y-crisis-de-fe.jpg', 3, 73,'https://drive.google.com/file/d/1eq-UrY7waYvshrQomcMIlfwdyAVCPEdd/view?usp=sharing',
      'FE Y CRISIS DE FE es en realidad dos libros complementarios: CRISIS DE FE y FE PARA HOY, diecisiete guias en total que facilitan una adecuada comprension de las alternativas propestas por Jesús a hombres y mujeres acosados por dudas y temores'),
  Documents('Alabanza y sabiduria', 'Marilyn Kunz & Catherine Schell',
      'Año: 1963', 'img_documents/alabanza-y-sabiduria.jpg', 3, 76,'https://drive.google.com/file/d/1d1-FimhjH3MtOSyDI9cUQP6ac6E9N6Q7/view?usp=sharing',
      'El estudio biblico de Salmos y Proverbios tiene algo caracteristico que lo diferencia de cualquier otro tipo de estudio por ejemplo, de porciones narrativas o didacticas y aun de las mismas epitolas. Por su propia naturaleza, la poesia permite al lector compartir intimamente las esperanzas, los temores, la tristeza y las alegrias del poeta. Esta es una guia de encuentros biblicos absolutamente indispensable para el crecimiento y la amistad en los creyentes'),
  Documents('Cuatro hombres de Dios ', 'Marilyn Kunz & Catherine Schell',
      'Año: 1965', 'img_documents/cuatro-hombres.jpg', 3, 86,'https://drive.google.com/file/d/1UrSc9ZwhPkpxn_Z3Gcz3pxxkFHwDNhk1/view?usp=sharing',
      'La fe obediente de Abraham, la misericordia de Jose, la mansedumbre y el amor sacrificial de Moises, y finalmente , la humildad de David, testimonian el cuidado y el cariño de Dios para con su pueblo Israel. CUATRO HOMBRES DE DIOS es una guia de encuentros biblicos que invita al cristiano a compartir y disfrutar aquellas bendiciones'),
  Documents('Vivir por la fe', 'Marilyn Kunz & Catherine Schell',
      'Año: 1974', 'img_documents/vivir-por-la-fe.jpg', 3, 60,'https://drive.google.com/file/d/1vHuMxLBZxM7UC8proho99riH-ihJPHgB/view?usp=sharing',
      'De entre todas las cartas del APostol Pablo, ninguna explica con mayor claridad los elemntos basicos del Evangelio de Jesucristo que la epistola a Romanos.'),
  Documents('Sufrimiento el peregrinaje de Job', 'Rodolfo Arena & Juan Harrower',
      'Año: 1988', 'img_documents/sufrimiento.jpg', 3, 42,'https://drive.google.com/file/d/1EEqUaeUBbA-ICPT2yuHMS6D7-MJPOW49/view?usp=sharing',
      'Cuando las prsonas "inocentes" sufren, escuchamos a los hombres quejarse a gritos ¿Por que? En estos  8 estudios exploramos junto con Job y sus amigos el problema del sufrimiento. A traves de la experiencia de Job, captamos de nuevo la grandeza de Dios'),
 
];
